// Code generated by "stringer -type=LifeStatus"; DO NOT EDIT.

package entities

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Alive-0]
	_ = x[Dead-1]
}

const _LifeStatus_name = "AliveDead"

var _LifeStatus_index = [...]uint8{0, 5, 9}

func (i LifeStatus) String() string {
	if i < 0 || i >= LifeStatus(len(_LifeStatus_index)-1) {
		return "LifeStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _LifeStatus_name[_LifeStatus_index[i]:_LifeStatus_index[i+1]]
}
