// Code generated by "stringer -type=Status"; DO NOT EDIT.

package entities

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Caos-0]
	_ = x[Extinction-1]
	_ = x[Static-2]
	_ = x[Oscillator-3]
	_ = x[InfiniteGrowth-4]
	_ = x[LimitedGrowth-5]
}

const _Status_name = "CaosExtinctionStaticOscillatorInfiniteGrowthLimitedGrowth"

var _Status_index = [...]uint8{0, 4, 14, 20, 30, 44, 57}

func (i Status) String() string {
	if i < 0 || i >= Status(len(_Status_index)-1) {
		return "Status(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Status_name[_Status_index[i]:_Status_index[i+1]]
}
