// Code generated by "stringer -type=Transition"; DO NOT EDIT.

package entities

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UnderPopulation-0]
	_ = x[LivesOn-1]
	_ = x[OverPopulation-2]
	_ = x[Reproduction-3]
	_ = x[RemainsDead-4]
}

const _Transition_name = "UnderPopulationLivesOnOverPopulationReproductionRemainsDead"

var _Transition_index = [...]uint8{0, 15, 22, 36, 48, 59}

func (i Transition) String() string {
	if i < 0 || i >= Transition(len(_Transition_index)-1) {
		return "Transition(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Transition_name[_Transition_index[i]:_Transition_index[i+1]]
}
